apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleesah-skattekart
  namespace: leesah
spec:
  port: 3000
  ingresses:
    - "https://pleesah-skattekart.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "10m"
      memory: 128Mi
  env:
    - name: VITE_API_URL
      value: http://pleesah-havnesjef
  accessPolicy:
    outbound:
      rules:
        - application: pleesah-havnesjef